myproject/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
 path('display/', views.userDetails, name='userDetails'),   
 path('booking/bookdetails/', views.bookdetails, name='bookdetails'),
 path('book/<int:id>', views.delete, name='delete'),
 path('products/', views.products, name='products'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('booking.urls', namespace='booking')),
]

myproject/service/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
  path('products/', views.products, name='products'),
  path('products/<int:id>', views.product_details, name='product_details'),
  path('products/add', views.add_product, name='add_product'),
  path('products/update/<int:id>', views.update_product, name='update_product'),
  path('products/delete/<int:id>', views.delete_product, name='delete_product'),
  path('booking/', views.booking, name='booking'),
  path('about/', views.about, name='about'),
  path('services/', views.services, name='services'),
  path('contact/', views.contact, name='contact'),
  path('adminpanel1/', views.adminpanel1, name='adminpanel1'),
  path('adminpanel2/', views.adminpanel2, name='adminpanel2'),
  path('appointment/', views.appointment, name='appointment'),
  path('', views.index, name='service'),
]

myproject/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'users'

urlpatterns = [
  path('login/', authentication_views.LoginView.as_view(template_name='users/admin.html'), name='login'),
  path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

myproject/service/models.py
from django.db import models
from operator import mod
from unittest.util import _MAX_LENGTH

# Create your models here.

class Product(models.Model):
  name = models.CharField(max_length=100)
  price = models.FloatField()
  description = models.CharField(max_length=100)

myproject/service/templates/service/views.py
from django.shortcuts import render, redirect
from contextlib import redirect_stderr
from http.client import HTTPResponse
from django.http import HttpResponse
from .models import Product

from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
  return render(request, 'myapp/homepage.html')

def booking(request):
  return render(request, 'myapp/bookingsalon.html')

def about(request):
  return render(request, 'myapp/About.html')

def services(request):
  return render(request, 'myapp/service.html')

def contact(request):
  return render(request, 'myapp/Contact.html')

def adminpanel1(request):
  return render(request, 'myapp/adminpanel1.html')

def adminpanel2(request):
  return render(request, 'myapp/Adminpanel2.html')

def appointment(request):
  return render(request, 'myapp/appointment.html')

@login_required
def products(request):
  products = Product.objects.all()
  context = {
    'products': products,
  }
  return render(request, 'myapp/adminpanel1.html', context)
  
@login_required
def product_details(request, id):
  product = Product.objects.get(id=id)
  context = {
    'product': product,
  }
  return render(request, 'myapp/details.html', context)

@login_required
def add_product(request):
  if request.method == 'POST':
    name = request.POST.get('name')
    price = request.POST.get('price')
    description = request.POST.get('description')
    product = Product(name=name, price=price, description=description)
    product.save()
  return render(request, 'myapp/addproduct.html')

def update_product(request, id):
  product = Product.objects.get(id=id)
  if request.method == 'POST':
    product.name = request.POST.get('name')
    product.price = request.POST.get('price')
    product.description = request.POST.get('description')
    product.save()
    return redirect('/myapp/products')
  context = {
    'product': product,
  }
  return render(request, 'myapp/updateproduct.html', context)

def delete_product(request, id):
  product = Product.objects.get(id=id)
  context = {
    'product': product,
  }
  if request.method == 'POST':
    product.delete()
    return redirect('/myapp/products')
  return render(request, 'myapp/deleteproduct.html', context)
  

myproject/service/views.py
from django.shortcuts import render, redirect
from contextlib import redirect_stderr
from http.client import HTTPResponse
from django.http import HttpResponse
from .models import Product

from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
  return render(request, 'service/homepage.html')

def booking(request):
  return render(request, 'service/bookingsalon.html')

def about(request):
  return render(request, 'service/About.html')

def services(request):
  return render(request, 'service/service.html')

def contact(request):
  return render(request, 'service/Contact.html')

def adminpanel1(request):
  return render(request, 'service/adminpanel1.html')

def adminpanel2(request):
  return render(request, 'service/Adminpanel2.html')

def appointment(request):
  return render(request, 'service/appointment.html')

@login_required
def products(request):
  products = Product.objects.all()
  context = {
    'products': products,
  }
  return render(request, 'service/adminpanel1.html', context)
  
@login_required
def product_details(request, id):
  product = Product.objects.get(id=id)
  context = {
    'product': product,
  }
  return render(request, 'service/details.html', context)

@login_required
def add_product(request):
  if request.method == 'POST':
    name = request.POST.get('name')
    price = request.POST.get('price')
    description = request.POST.get('description')
    product = Product(name=name, price=price, description=description)
    product.save()
  return render(request, 'service/addproduct.html')

def update_product(request, id):
  product = Product.objects.get(id=id)
  if request.method == 'POST':
    product.name = request.POST.get('name')
    product.price = request.POST.get('price')
    product.description = request.POST.get('description')
    product.save()
    return redirect('/service/products')
  context = {
    'product': product,
  }
  return render(request, 'service/updateproduct.html', context)

def delete_product(request, id):
  product = Product.objects.get(id=id)
  context = {
    'product': product,
  }
  if request.method == 'POST':
    product.delete()
    return redirect('/service/products')
  return render(request, 'service/deleteproduct.html', context)

myproject/service/templates/service/About.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="icon" href="{% static 'images/about.png' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
</head>

<body>
    <div class="main">
        <div class="navbar">
            <div class="icon">
                <h2 class="logo">VIDAsalon</h2>
            </div>

            <div class="menu">
                <ul>
                    <li><a href="{% url 'service:service'%}">HOME</a></li>
                    <li><a class="home-active" href="{% url 'service:about' %}">ABOUT</a></li>
                    <li><a href="{% url 'service:services' %}">SERVICE</a></li>
                    <li><a href="{% url 'service:contact' %}">CONTACT</a></li>
                    <li><a href="{% url 'users:login' %}">ADMIN</a></li>
                </ul>
            </div>
        </div> 
        <div class="content">
            <h1><span>WHOEVER YOU ARE.</span> <br>WHATEVER YOU DO. <br><span>WE BRING OUT THE BEST IN YOU.</span> <br><h3><br>VIDAsalon offers world-class hairdressing, fueled by Filipino passion.</h3></h1>
            <p class="par"><br>With the vision of bringing Fine European hairdressing to the Philippines, Offering a wide range of hair and beauty services to a wide range of customers. It is a name that has been admired and followed by many Filipinos since its first salon opened in 1989. It is now the biggest chain of salons in the Philippines, with over 200 branches all over the country. 
                “We take pride in providing the highest quality of service at prices everyone can afford,” says Charlton. VIDAsalon roster of services include Hair Styling, Hair Color, Hair and Scalp Treatments, Perming, Relaxing, Rebonding, Make Up, Waxing/Threading, Nail Care, and Hand and Foot Spas.
                A trusted salon brand such as VIDAsalon works with different trusted supliers for hair color, hair care, and other forms of technologies used for hair styling. Among these suppliers are L’Oreal, USA’s Professional MATRIX, Affinage Infiniti, and Schwarzkopf & Henkel.
                Total customers satisfaction is the goal of VIDAsalon. The VIDAsalon Experience is one where customers are given a relaxing ambience, professional consultations from creative stylists, and personal assistance by store managers and store assistants
                Clients are pampered as they are given quality service with professional care coming from a well-trained team. VIDAsalon has a solid core business management team equipped themselves with the latest and most innovative European hairdressing technology, which they generously and systematically pass on to every VIDAsalon stylist.
            </p>
                    </div>
                </div>
        </div>
    </div>
</body>
</html> 

myproject/service/templates/service/Adminpanel2.html
<!--BOOKING ONLY FOR ADMIN DASHBOARD-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Panel</title>
  <link rel="icon" href="{% static 'images/admin.png' %}" type="image/icon type">
  <link rel="stylesheet" href="{% static 'css/adminpanel2.css' %}">
</head>
<body>
  <div class="main">
		<div class="menu">
			<h2 id="logo"><img src="/static/images/loginmg.png" alt=""></h2>
			<a href="{% url 'service:products' %}">Dashboard</a>
			<a class="active" href="{% url 'booking:bookdetails' %}">Booking</a>
			{% if user.is_authenticated %}
			  <a class="logout" href="{% url 'users:logout'%}">Logout</a>
      {% endif %}
		</div>
		<div class="body">
			<table class="table">
        <thead class="thead-dark">
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Service</th>

            <th scope="col">Time</th>
            <th scope="col">Day</th>
        </thead>
				{% for book in bookdetails %}
          
          <tr scope="row">
            <td>{{book.Name}}</td>
            <td>{{book.Email}}</td>
            <td>{{book.Service}}</td>
            <td>{{book.Time}}</td>
            <td>{{book.Day}}</td>
            <td><a href="{% url 'booking:delete' book.id %}">Paid</a></td>
          </tr>

        {% endfor %}
      </table>
		</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</body>
</html>

myproject/service/templates/service/Contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Info</title>
    <link rel="icon" href="{% static 'images/contact.png' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
</head>

<body>
    <div class="main">
        <div class="navbar">
            <div class="icon">
                <h2 class="logo">VIDAsalon</h2>
            </div>

            <div class="menu">
                <ul>
                    <li><a href="{% url 'service:service'%}">HOME</a></li>
                    <li><a href="{% url 'service:about' %}">ABOUT</a></li>
                    <li><a href="{% url 'service:services' %}">SERVICE</a></li>
                    <li><a class="home-active" href="{% url 'service:contact' %}">CONTACT</a></li>
                    <li><a href="{% url 'users:login' %}">ADMIN</a></li>
                </ul>
            </div>
        </div> 
        <div class="content">
            <span><br>Do you have anything in your mind to tell us? Please don’t hesitate to get in touch to us via our contact form.</span>
            <p class="par"><h2><br>Head Office Opening Hour 8:00 AM – 5:00 PM
            <br> @ KCC Zamboanga 3rd Floor Gov.Camins Rd, Zamboanga, Zamboanga del Sur.</h2>
                <br>Email: <a href="jokelang.html">Vidasaloncorp@gmail.com</a>
                <br>Fb: Antonni Delos Reyes
                <br>Contact No. <a href="jokelang.html">+63 1234567891</a>
                <br>
                <br>or Visit the Webpage <a href="homepage.html">Vida Salon & SERVICES</a>
            </p>
                    </div>
                </div>
        </div>
    </div>
</body>
</html> 

myproject/service/templates/service/adminpanel1.html
<!--HOME ONLY FOR ADMIN DASHBOARD-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>Admin Panel</title>
    <link rel="icon" href="{% static 'images/admin.png' %}" />
    <link rel="stylesheet" href="{% static 'css/adminpanel1.css' %}" />
  </head>
  <body>
    <div class="main">
      <div class="menu">
        <h2 id="logo"><img src="/static/images/loginmg.png" alt="" /></h2>
        <a class="active" href="{% url 'service:products' %}">Dashboard</a>
        <a href="{% url 'booking:bookdetails' %}">Booking</a>
        {% if user.is_authenticated %}
        <a class="logout" href="{% url 'service:service' %}">Logout</a>
        {% endif %}
      </div>
      {% comment %} username {% endcomment %}
      <div class="username">
        <h2>Welcome {{user.username}}</h2>
      </div>
      <div class="add">
        <a href="{% url 'service:add_product' %}">Add New Product</a>
      </div>
      <div class="body">
        <table class="table">
          <thead class="thead-dark">
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Description</th>
          </thead>
          {% for product in products %}
          <tr scope="row">
            <td>{{product.name}}</td>
            <td>{{product.price}}</td>
            <td>{{product.description}}</td>
            <td>
              <a href="{% url 'service:product_details' product.id %}"
                >View Details</a
              >
            </td>
            <td>
              <a href="{% url 'service:update_product' product.id %}">Update</a>
            </td>
            <td>
              <a href="{% url 'service:delete_product' product.id %}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myproject/service/templates/service/appointment.html
<!--HOME ONLY FOR ADMIN DASHBOARD-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Panel</title>
  <link rel="icon" href="{% static 'images/admin.png' %}" type="image/icon type">
  <link rel="stylesheet" href="{% static 'css/appointment.css' %}">
</head>
<body>
  <div class="main">
		<div class="menu">
			<h2 id="logo"><img src="/static/images/loginmg.png" alt=""></h2>
			<a href="{% url 'service:adminpanel1' %}">Dashboard</a>
			<a href="{% url 'service:adminpanel2' %}">Booking</a>
			<a class="active" href="{% url 'service:appointment' %}">Appointment</a>
			{% if user.is_authenticated %}
			  <a href="{% url 'user:logout'%}">Logout</a>
      {% endif %}
		</div>
		<div class="body">
			<h1>Appointment here!</h1>
			<p>Lorem ipsum dolor sit amet. Aut error doloremque et natus rerum non iure dignissimos sit nisi voluptatem. Sit incidunt adipisci sit perferendis dicta non distinctio dolorem in voluptas laudantium et labore est obcaecati quibusdam!</p>
		</div>
	</div>
</body>
</html>

myproject/service/templates/service/bookingsalon.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Booking</title>
  <link rel="icon" href="{% static 'images/Booking.png' %}" type="image/icon type">
  <link rel="stylesheet" href="{% static 'css/bookingsalon.css' %}">
</head>
<body>
    <!-- This is main Form Area Start ++ -->
    <div class="bf-container">
      <!-- Main form Body Start -->
      <div class="bf-body">
          <!-- Form haed -->
          <div class="bf-head">
            <button class="back"><a href="{% url 'service:service' %}">&larr;</a></button>
            <h1>Booking Form</h1>
            <p>|-VidaSalon Book Now-|</p>
          </div>
          <!-- Form haed -->
          <!-- Form Body Box -->
          <form class="bf-body-box" action="form.php">
              <div class="bf-row">
                  <div class="bf-col-6">
                      <p>Your Name</p>
                      <input type="text" name="fname" id="fname" placeholder="Your Name">
                  </div>
                  <div class="bf-col-6">
                      <p>Email Address</p>
                      <input type="email" name="email" id="email" placeholder="Email Address">
                  </div>
              </div>
              <div class="bf-row">
                  <div class="bf-col-6 hair">
                      <p>Hair Selection</p>
                      <select name="s-select">
                          <option>Select</option>
                          <option value="1">&#9679;Hair Rebonding-$25</option>
                          <option value="2">&#9679;Hair Dye-$20</option>
                          <option value="3">&#9679;Hair Cut-$15</option>
                      </select>
                  </div>
                  <div class="bf-col-6 face">
                    <p>Face Selection</p>
                    <select name="s-select">
                        <option>Select</option>
                        <option value="1">&#9679;Masking-$15</option>
                        <option value="2">&#9679;Extraction-$18</option>
                        <option value="3">&#9679;Facial Massage-$35</option>
                    </select>
                </div>
                <div class="bf-col-6 nails">
                  <p>Nails Selection</p>
                  <select name="s-select">
                      <option>Select</option>
                      <option value="1">&#9679;Cut/Clean-$20</option>
                      <option value="2">&#9679;Foot Spa/Massage-$35</option>
                  </select>
              </div>
              </div>
              <div class="bf-row">
                <div class="bf-col-date">
                  <p>Select Date</p>
                  <input type="date" name="date" id="date">
              </div>
              <div class="bf-col-time">
                <p>Select Time</p>
                <input type="time" name="time" id="time">
              </div>
              <div class="bf-submit">
                  <div class="bf-col-3">
                      <input type="submit" id="submit" value="Submit">
                  </div>
              </div>
          </form>
          <!-- Form Body Box -->
      </div>
      <!-- Main form Body End -->
  </div>
  <!-- This is main Form Area  End -->
</body>
</html>

myproject/service/templates/service/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href=https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Details</title>
</head>
<body style="margin: 20px;">

    <h1>Product Details</h1>
    <div>{{product.name}}</div>
    <div>{{product.price}}</div>
    <div>{{product.description}}</div>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

myproject/service/templates/service/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Vida Salon</title>
    <link rel="icon" href="{% static 'images/scissor.png' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/stylehome.css' %}">
</head>
<body>
    <div class="main">
        <div class="navbar">
            <div class="icon">
                <h2 class="logo">VIDAsalon</h2>
            </div>

            <div class="menu">
                <ul>
                    <li><a class="home-active" href="{% url 'service:service'%}">HOME</a></li>
                    <li><a href="{% url 'service:about' %}">ABOUT</a></li>
                    <li><a href="{% url 'service:services' %}">SERVICE</a></li>
                    <li><a href="{% url 'service:contact' %}">CONTACT</a></li>
                    <li><a href="{% url 'users:login' %}">ADMIN</a></li>
                </ul>
            </div>
            <!--<div class="search">
                <input class="srch" type="search" name="" placeholder="Type To text">
                <a href="#"> <button class="btn">Search</button></a>
            </div>-->
            

        </div> 
        <div class="content">
            <h1>VIDA Salon & <br><span>SERVICES</span> <br><h3>All in one salon</h3></h1>
            <p class="par">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt neque 
                 expedita atque eveniet <br> quis nesciunt. Quos nulla vero consequuntur, fugit nemo ad delectus 
                <br> a quae totam ipsa illum minus laudantium?</p>

                <button class="cn"><a href="{% url 'booking:userDetails' %}">BOOK NOW</a></button>
				
                    </div>
                </div>
        </div>
    </div>
    
    <!--<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>-->
</body>
</html>

myproject/service/templates/service/service.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Service</title>
		<link rel="stylesheet" href="{% static 'css/service.css' %}" />
		<link rel="icon" href="{% static 'images/Services.png' %}" />
	</head>
	<body>
		<div class="main">
		<div class="navbar">
			<div class="icon">
			<h2 class="logo">VIDAsalon</h2>
			</div>

			<div class="menu">
			<ul>
				<li><a href="{% url 'service:service'%}">HOME</a></li>
				<li><a href="{% url 'service:about' %}">ABOUT</a></li>
				<li>
				<a class="service-active" href="{% url 'service:services' %}"
					>SERVICE</a
				>
				</li>
				<li><a href="{% url 'service:contact' %}">CONTACT</a></li>
				<li><a href="{% url 'users:login' %}">ADMIN</a></li>
			</ul>
			</div>
		</div>
		</div>

		<div class="slide-container">
		<span class="slider-span" id="slider-span1"></span>
		<span class="slider-span" id="slider-span2"></span>
		<span class="slider-span" id="slider-span3"></span>
		<span class="slider-span" id="slider-span4"></span>
		<span class="slider-span" id="slider-span5"></span>
		<span class="slider-span" id="slider-span6"></span>
		<span class="slider-span" id="slider-span7"></span>
		<span class="slider-span" id="slider-span8"></span>
		<span class="slider-span" id="slider-span9"></span>

		<div class="image-slider">
			<div class="slides-div" id="slide-1">
			<img
				src="{% static 'images/serviceimage/facemakeup.jpg'%}"
				class="img"
				id="img1"
			/>
			<h2 class="text1">Face Makeup<br />10$</h2>
			<a href="#slider-span1" class="button" id="button-1"></a>
			</div>
			<div class="slides-div" id="slide-2">
			<img
				src="{% static 'images/serviceimage/facialextraction.jpg' %}"
				class="img"
				id="img2"
			/>
			<h2 class="text1">Facial Extraction<br />12.99$</h2>
			<a href="#slider-span2" class="button" id="button-2"></a>
			</div>
			<div class="slides-div" id="slide-3">
			<img
				src="{% static 'images/serviceimage/facialmask.jpg' %}"
				class="img"
				id="img3"
			/>
			<h2 class="text1">Facial Mask<br />8.25$</h2>
			<a href="#slider-span3" class="button" id="button-3"></a>
			</div>
			<div class="slides-div" id="slide-4">
			<img
				src="{% static 'images/serviceimage/footmassge.jpg' %}"
				class="img"
				id="img4"
			/>
			<h2 class="text1">Foot Massage<br />15$</h2>
			<a href="#slider-span4" class="button" id="button-4"></a>
			</div>
			<div class="slides-div" id="slide-5">
			<img
				src="{% static 'images/serviceimage/footspa.jpg' %}"
				class="img"
				id="img5"
			/>
			<h2 class="text1">Foot Spa<br />10$</h2>
			<a href="#slider-span5" class="button" id="button-5"></a>
			</div>
			<div class="slides-div" id="slide-6">
			<img
				src="{% static 'images/serviceimage/haircut.jpg' %}"
				class="img"
				id="img6"
			/>
			<h2 class="text1">Haircut<br />7.99$</h2>
			<a href="#slider-span6" class="button" id="button-6"></a>
			</div>
			<div class="slides-div" id="slide-7">
			<img
				src="{% static 'images/serviceimage/hairdye.jpg' %}"
				class="img"
				id="img7"
			/>
			<h2 class="text1">Hair Dye<br />22$</h2>
			<a href="#slider-span7" class="button" id="button-7"></a>
			</div>
			<div class="slides-div" id="slide-8">
			<img
				src="{% static 'images/serviceimage/nails.jpg' %}"
				class="img"
				id="img8"
			/>
			<h2 class="text1">
				Nail Package<br />(manicure/pedicure)<br />13.15$
			</h2>
			<a href="#slider-span8" class="button" id="button-8"></a>
			</div>
			<div class="slides-div" id="slide-9">
			<img
				src="{% static 'images/serviceimage/rebonding.jpg' %}"
				class="img"
				id="img9"
			/>
			<h2 class="text1">Hair Rebond<br />20$</h2>
			<a href="#slider-span9" class="button" id="button-9"></a>
			</div>
		</div>
		</div>
	</body>
</html>